##### tmux.conf 

##### Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix


# Fast ESC for (Neo)Vim
set -sg escape-time 10

# allow extended keys
set -g extended-keys on

# Better editor/app integration
set -g focus-events on

# Truecolor
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB,screen-256color:RGB,tmux-256color:RGB"

# Nice numbering
set -g base-index 1
setw -g pane-base-index 1
set -g detach-on-destroy off
set -g renumber-windows on

# Vim-style tmux copy-mode
setw -g mode-keys vi

# begin “visual” selection with v
bind -T copy-mode-vi v send -X begin-selection  
# yank the selection and exit (like Vim’s y in visual mode)
bind -T copy-mode-vi y send -X copy-selection-and-cancel  
# yank current line (like Vim’s yy)
bind -T copy-mode-vi Y send -X copy-line  

# Splits/windows keep the current working directory
bind-key | split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"
bind-key c new-window       -c "#{pane_current_path}"
unbind '"'
unbind %

# Reload config
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# kill window without confirmation
unbind x
bind-key x kill-pane


# Mouse off (predictable; enable if you prefer)
set -g mouse on

##### Better pane navigation (vim-like)
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

## nvim like windows navigation - Switch tmux windows without prefix
set -sg escape-time 10
bind-key -n M-h previous-window
bind-key -n M-l next-window

## nvim-like session navigation - Switch tmux sessions without prefix
bind-key -n M-H switch-client -p
bind-key -n M-L switch-client -n

# create a new session either name it or have it named automatically
bind-key C command-prompt -p "New session name:" \
  "if-shell -F '#{==:%%,}' 'new-session -c \"#{pane_current_path}\"' 'new-session -s \"%%\" -c \"#{pane_current_path}\"'"

# create a new window on the right of the current one
bind-key v new-window -a -c "#{pane_current_path}"

# when create a new window make it start in home
unbind c
bind-key c new-window -c ~

## Bind Prefix + V to open a new pane running vim on the scrollback
bind V split-window -h "nvim <(tmux capture-pane -pS - -J)"
set -g history-limit 10000

## Minimal status bar: session on left, date/time on right
set -g status-position top
set -g status-interval 5
set -g status-left  "#[fg=green]#S#[default]"
set -g status-right "#[fg=black]%Y-%m-%d #[fg=black]%H:%M#[default]"

