#!/usr/bin/env bash
set -euo pipefail

# User-defined download links inputs

# Set to true to use the downloaded data as OpenMC's default cross sections
# and chain file.
SET_OPENMC_DEFAULTS=false

# chain
CHAIN_LINK="https://anl.box.com/shared/static/n0pkqe66uotskoljr93szvjyvtvycgze.xml"
INSTALLED_CHAIN="chain_endfb81_fast"

# cross sections
XS_LINK="https://anl.box.com/shared/static/6qr7jezzihkj9p9esl5jn19qgpujyjyz.xz"
INSTALLED_XS="xs_endfb81"

# data folder
OPENMC_BASE_DIR="${HOME}/openmc_data"

# Base directories
XS_DIR="${OPENMC_BASE_DIR}/${INSTALLED_XS}"
CHAIN_DIR="${OPENMC_BASE_DIR}/${INSTALLED_CHAIN}"

mkdir -p "${OPENMC_BASE_DIR}"
mkdir -p "${CHAIN_DIR}"

cd "${OPENMC_BASE_DIR}"

# Download and extract cross section data (skip if cross sections are already there)
if [ ! -e "${XS_DIR}/cross_sections.xml" ]; then
  XS_STAGING_DIR="$(mktemp -d "${OPENMC_BASE_DIR}/.xs-download.XXXXXX")"
  trap 'rm -rf -- "${XS_STAGING_DIR}"' EXIT

  curl -L "${XS_LINK}" \
    | tar -xJf - -C "${XS_STAGING_DIR}"

  EXTRACTED_XS_FILE="$(find "${XS_STAGING_DIR}" -type f -name cross_sections.xml -print -quit)"
  if [ -z "${EXTRACTED_XS_FILE}" ]; then
    echo "Error: downloaded cross-section archive does not contain cross_sections.xml" >&2
    exit 1
  fi
  if [ -e "${XS_DIR}" ]; then
    echo "Error: ${XS_DIR} exists but does not contain cross_sections.xml" >&2
    exit 1
  fi

  mv -- "$(dirname "${EXTRACTED_XS_FILE}")" "${XS_DIR}"
  rm -rf -- "${XS_STAGING_DIR}"
  trap - EXIT
fi

CROSS_SECTIONS_PATH="$(realpath "${XS_DIR}/cross_sections.xml")"
XS_VARIABLE_NAME="${INSTALLED_XS^^}"
XS_VARIABLE_NAME="${XS_VARIABLE_NAME//[^A-Z0-9_]/_}"

# Download chain file (always refresh; change if you want caching)
curl -L -o "${CHAIN_DIR}/${INSTALLED_CHAIN}.xml" \
	"${CHAIN_LINK}"

CHAIN_FILE_PATH="$(realpath "${CHAIN_DIR}/${INSTALLED_CHAIN}.xml")"
CHAIN_VARIABLE_NAME="${INSTALLED_CHAIN^^}"
CHAIN_VARIABLE_NAME="${CHAIN_VARIABLE_NAME//[^A-Z0-9_]/_}"

# Write the exports to a dedicated ~/.zsh drop-in (sourced by the chezmoi-managed
# ~/.zshrc, which must not be edited directly). Overwritten with the current
# paths on every run.
mkdir -p "${HOME}/.zsh"
cat > "${HOME}/.zsh/openmc.zsh" <<EOF
# OpenMC data paths (generated by openmc_data_fetcher.sh)
export ${XS_VARIABLE_NAME}="${CROSS_SECTIONS_PATH}"
export ${CHAIN_VARIABLE_NAME}="${CHAIN_FILE_PATH}"
EOF

if [[ "${SET_OPENMC_DEFAULTS}" == true ]]; then
  cat >> "${HOME}/.zsh/openmc.zsh" <<EOF
export OPENMC_CROSS_SECTIONS="${CROSS_SECTIONS_PATH}"
export OPENMC_CHAIN_FILE="${CHAIN_FILE_PATH}"
EOF
  echo "OPENMC_CROSS_SECTIONS=${CROSS_SECTIONS_PATH}"
  echo "OPENMC_CHAIN_FILE=${CHAIN_FILE_PATH}"
fi

echo "${XS_VARIABLE_NAME}=${CROSS_SECTIONS_PATH}"
echo "${CHAIN_VARIABLE_NAME}=${CHAIN_FILE_PATH}"
echo "Wrote ${HOME}/.zsh/openmc.zsh — restart your shell or run: source ~/.zshrc"
